# Stage 1: Build the application
FROM maven AS build
WORKDIR /app

# Copy only the pom.xml and source files needed to build
COPY pom.xml ./
COPY src ./src

# Build the project and skip tests for faster build
RUN mvn clean package -DskipTests

# Stage 2: Create a lightweight runtime container
FROM openjdk:17-alpine
WORKDIR /app
EXPOSE 8083

# Copy the JAR file from the build stage
COPY --from=build /app/target/notify-0.0.1-SNAPSHOT.jar notify-0.0.1-SNAPSHOT.jar

# Run the application
ENTRYPOINT ["java", "-jar", "notify-0.0.1-SNAPSHOT.jar"]
