# Stage 1: Build the application
FROM maven AS build
WORKDIR /app

# Copy only the pom.xml and source files needed to build
COPY pom.xml ./
COPY src ./src

# Build the project and skip tests for faster build
RUN mvn clean package -DskipTests -Dmaven.wagon.http.timeout=60000 -Dhttp.keepAlive=false


# Stage 2: Create a lightweight runtime container
FROM openjdk:17-alpine
WORKDIR /app
EXPOSE 8082

# Copy the JAR file from the build stage
COPY --from=build /app/target/workshop-0.0.1-SNAPSHOT.jar workshop-0.0.1-SNAPSHOT.jar

# Run the application
ENTRYPOINT ["java", "-jar", "workshop-0.0.1-SNAPSHOT.jar"]
